#ifndef __LNDC01_PINS_H
#define __LNDC01_PINS_H

#ifdef __cplusplus
extern "C"
{
#endif

// Настройки линий ввода/вывода платы LNDC v1.01 на базе микроконтроллера MKE18F512VLL16 
const T_IO_pins_configuration LNDC01_pins_conf[] =
{
//  gpio   port     num  irqc       lock mux    DSE      ODE     PFE      PUPD      dir     init
  { GPIOA, PORTA,   0,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         79 PTA0 Def=ADC0_SE0/ACMP0_IN0 ALT0=ADC0_SE0/ACMP0_IN0 ALT1=PTA0 ALT2=FTM2_CH1 ATL3=LPI2C0_SCLS ALT4=FXIO_D2 ALT5=FTM2_QD_PHA ALT6=LPUART0_CTS ALT7=TRGMUX_OUT3 
  { GPIOA, PORTA,   1,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         78 PTA1 Def=ADC0_SE1/ACMP0_IN1 ALT0=ADC0_SE1/ACMP0_IN1 ALT1=PTA1 ALT2=FTM1_CH1 ATL3=LPI2C0_SDAS ALT4=FXIO_D3 ALT5=FTM1_QD_PHA ALT6=LPUART0_RTS ALT7=TRGMUX_OUT0 
  { GPIOA, PORTA,   2,   IRQ_DIS,   0,   ALT6,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //UART0_RX  73 PTA2 Def=ADC1_SE0 ALT0=ADC1_SE0 ALT1=PTA2 ALT2=FTM3_CH0 ATL3=LPI2C0_SDA ALT4=EWM_OUT_b ALT5= ALT6=LPUART0_RX ALT7=                                           
  { GPIOA, PORTA,   3,   IRQ_DIS,   0,   ALT6,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //UART0_TX  72 PTA3 Def=ADC1_SE1 ALT0=ADC1_SE1 ALT1=PTA3 ALT2=FTM3_CH1 ATL3=LPI2C0_SCL ALT4=EWM_IN ALT5= ALT6=LPUART0_TX ALT7=                                              
//{ GPIOA, PORTA,   4,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SWD_DIO   98 PTA4 Def=JTAG_TMS/SWD_DIO ALT0= ALT1=PTA4 ALT2= ATL3= ALT4=ACMP0_OUT ALT5=EWM_OUT_b ALT6= ALT7=JTAG_TMS/SWD_DIO                                              
//{ GPIOA, PORTA,   5,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //Reset     97 PTA5 Def=RESET_b ALT0= ALT1=PTA5 ALT2= ATL3=TCLK1 ALT4= ALT5= ALT6=JTAG_TRST_b ALT7=RESET_b                                                                  
  { GPIOA, PORTA,   6,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //INESC3    58 PTA6 Def=ADC0_SE2/ACMP1_IN0 ALT0=ADC0_SE2/ACMP1_IN0 ALT1=PTA6 ALT2=FTM0_FLT1 ATL3=LPSPI1_PCS1 ALT4= ALT5= ALT6=LPUART1_CTS ALT7=                             
  { GPIOA, PORTA,   7,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //INESC4    57 PTA7 Def=ADC0_SE3/ACMP1_IN1 ALT0=ADC0_SE3/ACMP1_IN1 ALT1=PTA7 ALT2=FTM0_FLT2 ATL3= ALT4=RTC_CLKIN ALT5= ALT6=LPUART1_RTS ALT7=                               
  { GPIOA, PORTA,   8,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         100 PTA8 Def=DISABLED ALT0= ALT1=PTA8 ALT2= ATL3= ALT4=FXIO_D6 ALT5=FTM3_FLT3 ALT6= ALT7=                                                                       
  { GPIOA, PORTA,   9,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         99 PTA9 Def=DISABLED ALT0= ALT1=PTA9 ALT2= ATL3= ALT4=FXIO_D7 ALT5=FTM3_FLT2 ALT6=FTM1_FLT3 ALT7=                                                               
//{ GPIOA, PORTA,  10,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SWO       92 PTA10 Def=JTAG_TDO/noetm_Trace_SWO ALT0= ALT1=PTA10 ALT2=FTM1_CH4 ATL3=LPUART0_TX ALT4=FXIO_D0 ALT5= ALT6= ALT7=JTAG_TDO/noetm_Trace_SWO                     
  { GPIOA, PORTA,  11,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         91 PTA11 Def=DISABLED ALT0= ALT1=PTA11 ALT2=FTM1_CH5 ATL3=LPUART0_RX ALT4=FXIO_D1 ALT5= ALT6= ALT7=                                                             
  { GPIOA, PORTA,  12,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //LNDSV     90 PTA12 Def=ADC2_SE5 ALT0=ADC2_SE5 ALT1=PTA12 ALT2=FTM1_CH6 ATL3=CAN1_RX ALT4=LPI2C1_SDAS ALT5= ALT6= ALT7=                                                    
  { GPIOA, PORTA,  13,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SLNDV     89 PTA13 Def=ADC2_SE4 ALT0=ADC2_SE4 ALT1=PTA13 ALT2=FTM1_CH7 ATL3=CAN1_TX ALT4=LPI2C1_SCLS ALT5= ALT6= ALT7=                                                    
  { GPIOA, PORTA,  14,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         88 PTA14 Def=DISABLED ALT0= ALT1=PTA14 ALT2=FTM0_FLT0 ATL3=FTM3_FLT1 ALT4=EWM_IN ALT5= ALT6=FTM1_FLT0 ALT7=BUSOUT                                               
  { GPIOA, PORTA,  15,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SLNDI     83 PTA15 Def=ADC1_SE12 ALT0=ADC1_SE12 ALT1=PTA15 ALT2=FTM1_CH2 ATL3=LPSPI0_PCS3 ALT4= ALT5= ALT6= ALT7=                                                         
  { GPIOA, PORTA,  16,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //CANCTRL   82 PTA16 Def=ADC1_SE13 ALT0=ADC1_SE13 ALT1=PTA16 ALT2=FTM1_CH3 ATL3=LPSPI1_PCS2 ALT4= ALT5= ALT6= ALT7=                                                         
  { GPIOA, PORTA,  17,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         62 PTA17 Def=DISABLED ALT0= ALT1=PTA17 ALT2=FTM0_CH6 ATL3=FTM3_FLT0 ALT4=EWM_OUT_b ALT5= ALT6= ALT7=                                                            
                                                                                    
  { GPIOB, PORTB,   0,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //INESC1    54 PTB0  Def=ADC0_SE4 ALT0=ADC0_SE4 ALT1=PTB0 ALT2=LPUART0_RX ATL3=LPSPI0_PCS0 ALT4=LPTMR0_ALT3 ALT5=PWT_IN3 ALT6= ALT7=   
  { GPIOB, PORTB,   1,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //INESC2    53 PTB1  Def=ADC0_SE5 ALT0=ADC0_SE5 ALT1=PTB1 ALT2=LPUART0_TX ATL3=LPSPI0_SOUT ALT4=TCLK0 ALT5= ALT6= ALT7=                
  { GPIOB, PORTB,   2,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //INVPWR    48 PTB2  Def=ADC0_SE6 ALT0=ADC0_SE6 ALT1=PTB2 ALT2=FTM1_CH0 ATL3=LPSPI0_SCK ALT4=FTM1_QD_PHB ALT5= ALT6=TRGMUX_IN3 ALT7=   
  { GPIOB, PORTB,   3,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //IN5V      47 PTB3  Def=ADC0_SE7 ALT0=ADC0_SE7 ALT1=PTB3 ALT2=FTM1_CH1 ATL3=LPSPI0_SIN ALT4=FTM1_QD_PHA ALT5= ALT6=TRGMUX_IN2 ALT7=   
  { GPIOB, PORTB,   4,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //SEG_A     28 PTB4  Def=ACMP1_IN2 ALT0=ACMP1_IN2 ALT1=PTB4 ALT2=FTM0_CH4 ATL3=LPSPI0_SOUT ALT4= ALT5= ALT6=TRGMUX_IN1 ALT7=           
  { GPIOB, PORTB,   5,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //SEG_B     27 PTB5  Def=DISABLED ALT0= ALT1=PTB5 ALT2=FTM0_CH5 ATL3=LPSPI0_PCS1 ALT4= ALT5= ALT6=TRGMUX_IN0 ALT7=ACMP1_OUT            
//{ GPIOB, PORTB,   6,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //XTAL      16 PTB6  Def=XTAL ALT0=XTAL ALT1=PTB6 ALT2=LPI2C0_SDA ATL3= ALT4= ALT5= ALT6= ALT7=                                        
//{ GPIOB, PORTB,   7,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //EXTAL     15 PTB7  Def=EXTAL ALT0=EXTAL ALT1=PTB7 ALT2=LPI2C0_SCL ATL3= ALT4= ALT5= ALT6= ALT7=                                      
  { GPIOB, PORTB,   8,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         77 PTB8  Def=ADC2_SE11 ALT0=ADC2_SE11 ALT1=PTB8 ALT2=FTM3_CH0 ATL3= ALT4= ALT5= ALT6= ALT7=                                
  { GPIOB, PORTB,   9,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         76 PTB9  Def=ADC2_SE10 ALT0=ADC2_SE10 ALT1=PTB9 ALT2=FTM3_CH1 ATL3=LPI2C0_SCLS ALT4= ALT5= ALT6= ALT7=                     
  { GPIOB, PORTB,  10,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         75 PTB10 Def=ADC2_SE9 ALT0=ADC2_SE9 ALT1=PTB10 ALT2=FTM3_CH2 ATL3=LPI2C0_SDAS ALT4= ALT5= ALT6= ALT7=                      
  { GPIOB, PORTB,  11,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         74 PTB11 Def=ADC2_SE8 ALT0=ADC2_SE8 ALT1=PTB11 ALT2=FTM3_CH3 ATL3=LPI2C0_HREQ ALT4= ALT5= ALT6= ALT7=                      
  { GPIOB, PORTB,  12,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         68 PTB12 Def=ADC1_SE7 ALT0=ADC1_SE7 ALT1=PTB12 ALT2=FTM0_CH0 ATL3=FTM3_FLT2 ALT4= ALT5= ALT6= ALT7=                        
  { GPIOB, PORTB,  13,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //EN_EXTS   67 PTB13 Def=ADC1_SE8 ALT0=ADC1_SE8 ALT1=PTB13 ALT2=FTM0_CH1 ATL3=FTM3_FLT1 ALT4= ALT5= ALT6= ALT7=                        
  { GPIOB, PORTB,  14,   IRQ_DIS,   0,   ALT3,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SPI1_SCK  66 PTB14 Def=ADC1_SE9 ALT0=ADC1_SE9 ALT1=PTB14 ALT2=FTM0_CH2 ATL3=LPSPI1_SCK ALT4= ALT5= ALT6= ALT7=                       
  { GPIOB, PORTB,  15,   IRQ_DIS,   0,   ALT3,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SPI1_SIN  65 PTB15 Def=ADC1_SE14 ALT0=ADC1_SE14 ALT1=PTB15 ALT2=FTM0_CH3 ATL3=LPSPI1_SIN ALT4= ALT5= ALT6= ALT7=                     
  { GPIOB, PORTB,  16,   IRQ_DIS,   0,   ALT3,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SPI1_SOUT 64 PTB16 Def=ADC1_SE15 ALT0=ADC1_SE15 ALT1=PTB16 ALT2=FTM0_CH4 ATL3=LPSPI1_SOUT ALT4= ALT5= ALT6= ALT7=                    
  { GPIOB, PORTB,  17,   IRQ_DIS,   0,   ALT3,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SPI1_PCS3 63 PTB17 Def=ADC2_SE3 ALT0=ADC2_SE3 ALT1=PTB17 ALT2=FTM0_CH5 ATL3=LPSPI1_PCS3 ALT4= ALT5= ALT6= ALT7=                      
                                                                                 
  { GPIOC, PORTC,   0,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //DSENS     40 PTC0  Def=ADC0_SE8/ACMP1_IN4 ALT0=ADC0_SE8/ACMP1_IN4 ALT1=PTC0 ALT2=FTM0_CH0 ATL3= ALT4= ALT5= ALT6=FTM1_CH6 ALT7=                            
  { GPIOC, PORTC,   1,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         39 PTC1  Def=ADC0_SE9/ACMP1_IN3 ALT0=ADC0_SE9/ACMP1_IN3 ALT1=PTC1 ALT2=FTM0_CH1 ATL3= ALT4= ALT5= ALT6=FTM1_CH7 ALT7=                            
  { GPIOC, PORTC,   2,   IRQ_DIS,   0,   ALT3,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //CAN0_RX   30 PTC2  Def=ADC0_SE10/ACMP0_IN5/XTAL32 ALT0=ADC0_SE10/ACMP0_IN5/XTAL32 ALT1=PTC2 ALT2=FTM0_CH2 ATL3=CAN0_RX ALT4= ALT5= ALT6= ALT7=             
  { GPIOC, PORTC,   3,   IRQ_DIS,   0,   ALT3,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //CAN0_TX   29 PTC3  Def=ADC0_SE11/ACMP0_IN4/EXTAL32 ALT0=ADC0_SE11/ACMP0_IN4/EXTAL32 ALT1=PTC3 ALT2=FTM0_CH3 ATL3=CAN0_TX ALT4= ALT5= ALT6= ALT7=           
//{ GPIOC, PORTC,   4,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SWD_CLK   96 PTC4  Def=JTAG_TCLK/SWD_CLK ALT0=ACMP0_IN2 ALT1=PTC4 ALT2=FTM1_CH0 ATL3=RTC_CLKOUT ALT4= ALT5=EWM_IN ALT6=FTM1_QD_PHB ALT7=JTAG_TCLK/SWD_CLK  
  { GPIOC, PORTC,   5,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         95 PTC5  Def=JTAG_TDI ALT0= ALT1=PTC5 ALT2=FTM2_CH0 ATL3=RTC_CLKOUT ALT4=LPI2C1_HREQ ALT5= ALT6=FTM2_QD_PHB ALT7=JTAG_TDI                        
  { GPIOC, PORTC,   6,   IRQ_DIS,   0,   ALT3,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //CAN1_RX   81 PTC6  Def=ADC1_SE4 ALT0=ADC1_SE4 ALT1=PTC6 ALT2=LPUART1_RX ATL3=CAN1_RX ALT4=FTM3_CH2 ALT5= ALT6= ALT7=                                       
  { GPIOC, PORTC,   7,   IRQ_DIS,   0,   ALT3,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //CAN1_TX   80 PTC7  Def=ADC1_SE5 ALT0=ADC1_SE5 ALT1=PTC7 ALT2=LPUART1_TX ATL3=CAN1_TX ALT4=FTM3_CH3 ALT5= ALT6= ALT7=                                       
  { GPIOC, PORTC,   8,   IRQ_DIS,   0,   ALT6,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //UART0_CTS 56 PTC8  Def=ADC2_SE14 ALT0=ADC2_SE14 ALT1=PTC8 ALT2=LPUART1_RX ATL3=FTM1_FLT0 ALT4= ALT5= ALT6=LPUART0_CTS ALT7=                                
  { GPIOC, PORTC,   9,   IRQ_DIS,   0,   ALT6,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //UART0_RTS 55 PTC9  Def=ADC2_SE15 ALT0=ADC2_SE15 ALT1=PTC9 ALT2=LPUART1_TX ATL3=FTM1_FLT1 ALT4= ALT5= ALT6=LPUART0_RTS ALT7=                                
  { GPIOC, PORTC,  10,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //DSENSEN   52 PTC10 Def=DISABLED ALT0= ALT1=PTC10 ALT2=FTM3_CH4 ATL3= ALT4= ALT5= ALT6= ALT7=                                                               
  { GPIOC, PORTC,  11,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //OUT1      51 PTC11 Def=DISABLED ALT0= ALT1=PTC11 ALT2=FTM3_CH5 ATL3= ALT4= ALT5= ALT6= ALT7=                                                               
  { GPIOC, PORTC,  12,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //OUT2      50 PTC12 Def=DISABLED ALT0= ALT1=PTC12 ALT2=FTM3_CH6 ATL3=FTM2_CH6 ALT4= ALT5= ALT6= ALT7=                                                       
  { GPIOC, PORTC,  13,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //OUT3      49 PTC13 Def=DISABLED ALT0= ALT1=PTC13 ALT2=FTM3_CH7 ATL3=FTM2_CH7 ALT4= ALT5= ALT6= ALT7=                                                       
  { GPIOC, PORTC,  14,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         46 PTC14 Def=ADC0_SE12/ACMP2_IN5 ALT0=ADC0_SE12/ACMP2_IN5 ALT1=PTC14 ALT2=FTM1_CH2 ATL3= ALT4= ALT5= ALT6= ALT7=                                 
  { GPIOC, PORTC,  15,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         45 PTC15 Def=ADC0_SE13/ACMP2_IN4 ALT0=ADC0_SE13/ACMP2_IN4 ALT1=PTC15 ALT2=FTM1_CH3 ATL3= ALT4= ALT5= ALT6= ALT7=                                 
  { GPIOC, PORTC,  16,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         44 PTC16 Def=ADC0_SE14 ALT0=ADC0_SE14 ALT1=PTC16 ALT2=FTM1_FLT2 ATL3= ALT4=LPI2C1_SDAS ALT5= ALT6= ALT7=                                         
  { GPIOC, PORTC,  17,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         43 PTC17 Def=ADC0_SE15 ALT0=ADC0_SE15 ALT1=PTC17 ALT2=FTM1_FLT3 ATL3= ALT4=LPI2C1_SCLS ALT5= ALT6= ALT7=                                         
                                                                                
  { GPIOD, PORTD,   0,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //SEG_C     4  PTD0  Def=ADC2_SE0 ALT0=ADC2_SE0 ALT1=PTD0 ALT2=FTM0_CH2 ATL3=LPSPI1_SCK ALT4=FTM2_CH0 ALT5= ALT6=FXIO_D0 ALT7=TRGMUX_OUT1 
  { GPIOD, PORTD,   1,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //SEG_D     3  PTD1  Def=ADC2_SE1 ALT0=ADC2_SE1 ALT1=PTD1 ALT2=FTM0_CH3 ATL3=LPSPI1_SIN ALT4=FTM2_CH1 ALT5= ALT6=FXIO_D1 ALT7=TRGMUX_OUT2 
  { GPIOD, PORTD,   2,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //LEDESC1   71 PTD2  Def=ADC1_SE2 ALT0=ADC1_SE2 ALT1=PTD2 ALT2=FTM3_CH4 ATL3=LPSPI1_SOUT ALT4=FXIO_D4 ALT5= ALT6=TRGMUX_IN5 ALT7=         
  { GPIOD, PORTD,   3,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //LEDESC2   70 PTD3  Def=NMI_b ALT0=ADC1_SE3 ALT1=PTD3 ALT2=FTM3_CH5 ATL3=LPSPI1_PCS0 ALT4=FXIO_D5 ALT5= ALT6=TRGMUX_IN4 ALT7=NMI_b       
  { GPIOD, PORTD,   4,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //LANDBTN   69 PTD4  Def=ADC1_SE6/ACMP1_IN6 ALT0=ADC1_SE6/ACMP1_IN6 ALT1=PTD4 ALT2=FTM0_FLT3 ATL3=FTM3_FLT3 ALT4= ALT5= ALT6= ALT7=       
  { GPIOD, PORTD,   5,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //1WLED     33 PTD5  Def=DISABLED ALT0= ALT1=PTD5 ALT2=FTM2_CH3 ATL3=LPTMR0_ALT2 ALT4=FTM2_FLT1 ALT5=PWT_IN2 ALT6=TRGMUX_IN7 ALT7=        
  { GPIOD, PORTD,   6,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         32 PTD6  Def=DISABLED ALT0= ALT1=PTD6 ALT2=LPUART2_RX ATL3= ALT4=FTM2_FLT2 ALT5= ALT6= ALT7=                                  
  { GPIOD, PORTD,   7,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         31 PTD7  Def=DISABLED ALT0= ALT1=PTD7 ALT2=LPUART2_TX ATL3= ALT4=FTM2_FLT3 ALT5= ALT6= ALT7=                                  
  { GPIOD, PORTD,   8,   IRQ_DIS,   0,   ALT2,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //I2C1_SDA  42 PTD8  Def=DISABLED ALT0= ALT1=PTD8 ALT2=LPI2C1_SDA ATL3= ALT4=FTM2_FLT2 ALT5= ALT6=FTM1_CH4 ALT7=                          
  { GPIOD, PORTD,   9,   IRQ_DIS,   0,   ALT2,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //I2C1_SCL  41 PTD9  Def=ACMP1_IN5 ALT0=ACMP1_IN5 ALT1=PTD9 ALT2=LPI2C1_SCL ATL3= ALT4=FTM2_FLT3 ALT5= ALT6=FTM1_CH5 ALT7=                
  { GPIOD, PORTD,  10,   IRQ_DIS,   0,   ALT2,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SLND_T    36 PTD10 Def=DISABLED ALT0= ALT1=PTD10 ALT2=FTM2_CH0 ATL3=FTM2_QD_PHB ALT4= ALT5= ALT6= ALT7=                                 
  { GPIOD, PORTD,  11,   IRQ_DIS,   0,   ALT2,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //SLND_B    35 PTD11 Def=DISABLED ALT0= ALT1=PTD11 ALT2=FTM2_CH1 ATL3=FTM2_QD_PHA ALT4= ALT5= ALT6=LPUART2_CTS ALT7=                      
  { GPIOD, PORTD,  12,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //BT1       34 PTD12 Def=DISABLED ALT0= ALT1=PTD12 ALT2=FTM2_CH2 ATL3=LPI2C1_HREQ ALT4= ALT5= ALT6=LPUART2_RTS ALT7=                      
  { GPIOD, PORTD,  13,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //BT2       25 PTD13 Def=DISABLED ALT0= ALT1=PTD13 ALT2=FTM2_CH4 ATL3= ALT4= ALT5= ALT6= ALT7=RTC_CLKOUT                                  
  { GPIOD, PORTD,  14,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //BT3       24 PTD14 Def=DISABLED ALT0= ALT1=PTD14 ALT2=FTM2_CH5 ATL3= ALT4= ALT5= ALT6= ALT7=CLKOUT                                      
  { GPIOD, PORTD,  15,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //SEG_E     22 PTD15 Def=ACMP2_IN1 ALT0=ACMP2_IN1 ALT1=PTD15 ALT2=FTM0_CH0 ATL3= ALT4= ALT5= ALT6= ALT7=                                  
  { GPIOD, PORTD,  16,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //SEG_F     21 PTD16 Def=ACMP2_IN0 ALT0=ACMP2_IN0 ALT1=PTD16 ALT2=FTM0_CH1 ATL3= ALT4= ALT5= ALT6= ALT7=                                  
  { GPIOD, PORTD,  17,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //MUTE      20 PTD17 Def=DISABLED ALT0= ALT1=PTD17 ALT2=FTM0_FLT2 ATL3=LPUART2_RX ALT4= ALT5= ALT6= ALT7=                                 
                                                                       
  { GPIOE, PORTE,   0,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //SEG_G     94 PTE0  Def=ADC2_SE7 ALT0=ADC2_SE7 ALT1=PTE0 ALT2=LPSPI0_SCK ATL3=TCLK1 ALT4=LPI2C1_SDA ALT5= ALT6=FTM1_FLT2 ALT7=                       
  { GPIOE, PORTE,   1,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //SEG_H     93 PTE1  Def=ADC2_SE6 ALT0=ADC2_SE6 ALT1=PTE1 ALT2=LPSPI0_SIN ATL3=LPI2C0_HREQ ALT4=LPI2C1_SCL ALT5= ALT6=FTM1_FLT1 ALT7=                 
  { GPIOE, PORTE,   2,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         85 PTE2  Def=ADC1_SE10 ALT0=ADC1_SE10 ALT1=PTE2 ALT2=LPSPI0_SOUT ATL3=LPTMR0_ALT3 ALT4=FTM3_CH6 ALT5=PWT_IN3 ALT6=LPUART1_CTS ALT7=       
  { GPIOE, PORTE,   3,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //OK1       18 PTE3  Def=DISABLED ALT0= ALT1=PTE3 ALT2=FTM0_FLT0 ATL3=LPUART2_RTS ALT4=FTM2_FLT0 ALT5= ALT6=TRGMUX_IN6 ALT7=ACMP2_OUT                 
  { GPIOE, PORTE,   4,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //OK2       9  PTE4  Def=DISABLED ALT0= ALT1=PTE4 ALT2=BUSOUT ATL3=FTM2_QD_PHB ALT4=FTM2_CH2 ALT5=CAN0_RX ALT6=FXIO_D6 ALT7=EWM_OUT_b                 
  { GPIOE, PORTE,   5,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //OK3       8  PTE5  Def=DISABLED ALT0= ALT1=PTE5 ALT2=TCLK2 ATL3=FTM2_QD_PHA ALT4=FTM2_CH3 ALT5=CAN0_TX ALT6=FXIO_D7 ALT7=EWM_IN                     
  { GPIOE, PORTE,   6,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         84 PTE6  Def=ADC1_SE11/ACMP0_IN6 ALT0=ADC1_SE11/ACMP0_IN6 ALT1=PTE6 ALT2=LPSPI0_PCS2 ATL3= ALT4=FTM3_CH7 ALT5= ALT6=LPUART1_RTS ALT7=     
  { GPIOE, PORTE,   7,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         59 PTE7  Def=ADC2_SE2/ACMP2_IN6 ALT0=ADC2_SE2/ACMP2_IN6 ALT1=PTE7 ALT2=FTM0_CH7 ATL3=FTM3_FLT0 ALT4= ALT5= ALT6= ALT7=                    
  { GPIOE, PORTE,   8,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //-         26 PTE8  Def=ACMP0_IN3 ALT0=ACMP0_IN3 ALT1=PTE8 ALT2=FTM0_CH6 ATL3= ALT4= ALT5= ALT6= ALT7=                                               
  { GPIOE, PORTE,   9,   IRQ_DIS,   0,   ALT0,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_INP,   0 }, //AOUT      23 PTE9  Def=ACMP2_IN2/DAC0_OUT ALT0=ACMP2_IN2/DAC0_OUT ALT1=PTE9 ALT2=FTM0_CH7 ATL3=LPUART2_CTS ALT4= ALT5= ALT6= ALT7=                  
  { GPIOE, PORTE,  10,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //OUTEML    6  PTE10 Def=ADC2_SE12 ALT0=ADC2_SE12 ALT1=PTE10 ALT2=CLKOUT ATL3= ALT4=FTM2_CH4 ALT5= ALT6=FXIO_D4 ALT7=TRGMUX_OUT4                      
  { GPIOE, PORTE,  11,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //LEDESC3   5  PTE11 Def=ADC2_SE13 ALT0=ADC2_SE13 ALT1=PTE11 ALT2=PWT_IN1 ATL3=LPTMR0_ALT1 ALT4=FTM2_CH5 ALT5= ALT6=FXIO_D5 ALT7=TRGMUX_OUT5          
  { GPIOE, PORTE,  12,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //DS2484_EN 19 PTE12 Def=DISABLED ALT0= ALT1=PTE12 ALT2=FTM0_FLT3 ATL3=LPUART2_TX ALT4= ALT5= ALT6= ALT7=                                             
  { GPIOE, PORTE,  13,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //LEDESC4   7  PTE13 Def=DISABLED ALT0= ALT1=PTE13 ALT2= ATL3= ALT4=FTM2_FLT0 ALT5= ALT6= ALT7=                                                       
  { GPIOE, PORTE,  14,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //LEDLNDSW  17 PTE14 Def=ACMP2_IN3 ALT0=ACMP2_IN3 ALT1=PTE14 ALT2=FTM0_FLT1 ATL3= ALT4=FTM2_FLT1 ALT5= ALT6= ALT7=                                    
  { GPIOE, PORTE,  15,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //OBLED1    2  PTE15 Def=DISABLED ALT0= ALT1=PTE15 ALT2= ATL3= ALT4=FTM2_CH6 ALT5= ALT6=FXIO_D2 ALT7=TRGMUX_OUT6                                      
  { GPIOE, PORTE,  16,   IRQ_DIS,   0,   ALT1,  DSE_HI,  OD_DIS, PFE_DIS, PUPD_DIS, GP_OUT,   0 }, //OBLED2    1  PTE16 Def=DISABLED ALT0= ALT1=PTE16 ALT2= ATL3= ALT4=FTM2_CH7 ALT5= ALT6=FXIO_D3 ALT7=TRGMUX_OUT7                                      
};


#ifdef __cplusplus
}
#endif





























































#endif //



